---
- name: stop ec2 instance
  ec2:
    state: stopped
    wait: true
    instance_ids: "{{ ec2_instance_id }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_build_subnet }}"

- name: create ami
  ec2_ami:
    instance_id: "{{ ec2_instance_id }}"
    name: "{{ ec2_ami_name }}"
    region: "{{ aws_region }}"
    wait_timeout: 1500
    wait: yes
  register: ami

- name: terminate ec2 instance
  ec2:
    instance_ids: "{{ ec2_instance_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: ami|success
