---
- name: start ec2 instance
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    #iam_role: true
    #iam_role_name: "{{ env }}-build"
    keypair: "{{ env }}"
    instance_type: t2.micro
    group_id: "{{ aws_build_sg }}"
    image: ami-e05a4d84
    zone: "{{ aws_region }}a"
    assign_public_ip: true
    vpc_subnet_id: "{{ aws_build_subnet }}"
    monitoring: false
    wait: yes
    wait_timeout: 30
    instance_tags:
      Name: "{{ ec2_instance_name }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 20
        device_type: gp2
        delete_on_termination: true
  register: ec2

- set_fact:
    ec2_instance_id: "{{ ec2.instances[0].id }}"
    ec2_private_ip: "{{ ec2.instances[0].private_ip }}"
    ec2_public_ip: "{{ ec2.instances[0].public_ip }}"

- name: add access to create ec2 instance
  add_host:
    name: "{{ ec2_public_ip }}"
    groups: ec2_instance
    ansible_user: "centos"
    ansible_private_key_file: ./../shared/key-pairs/ssh.priv

- name: wait until ssh is available
  local_action:
    delay: 30
    module: wait_for
    host: "{{ ec2_public_ip }}"
    port: 22

