---
ops_tools_yum_pkgs:
  - bind-utils
  - bzip2
  - curl
  - git
  - htop
  - iftop
  - iotop
  - lshw
  - lsof
  - lzop
  - mailx
  - mlocate
  - nc
  - net-tools
  - nfs-utils
  - nmap
  - pciutils
  - procps
  - screen
  - setools
  - setroubleshoot
  - strace
  - tcpdump
  - telnet
  - tmux
  - tree
  - unzip
  - wget
  - vim
  - which
  - whois

